### ISSUE TITLE
VS2012 don't undestand DllExport attribute

### ISSUE THREAD

**Issue by ak964** [3F/Examples#1]
VS2012, C#.
Create ClassLibrary project, install DllExport 1.7.3 package, add function from example. Compiler can't find DllExport and DllExportAttribute.

What's wrong?

**Comment by ak964** [comment]
Namespace in DllExport.dll looks like this:
D3F00FF1770DED978EC774BA389F2DC901F4.B00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.C00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.D00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.E00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.F00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

[DllExport.zip](https://github.com/3F/Examples/files/5168598/DllExport.zip)

**Comment by ak964** [comment]
Such situation shown in [video](https://www.youtube.com/watch?v=sBWt-KdQtoc).
In my case it's slightly wrong: DllExport.bat lays not in project path (as in video), but deeper in \packages\DllExport.1.7.3.
Running from there it breaks the project, so VS can`t find DllExport.bat.
To solve the problem: copy DllExport.bat into project path (near sln file), run it, click Apply.

**Comment by 3F** [comment]
@ak964 

Not sure what you are trying to find in \packages folder but you need either getting DllExport.bat from [here](https://github.com/3F/DllExport/releases) or activation from [here](https://www.nuget.org/packages/DllExport/)

Your mentioned way is incorrect or just for not regular use.
Please simply follow the official steps - https://github.com/3F/DllExport/wiki/Quick-start

Thanks for using!

Please also note, this repo only for examples and for related things/problems.
You need to open an issue in the original project if you have something related to it - https://github.com/3F/DllExport/issues

Thanks,
