### ISSUE TITLE
Basic Export needs dotnetcore dependency checked

### ISSUE THREAD

**Issue by ZinojoDev** [3F/Examples#2]
I am brand new to .NET, so maybe this is a silly thing to post. I downloaded your BasicExport example and loaded it in Visual Studio to experiment with it. I could get the VB.net/C# .NET framework projects to display in the debug console properly, but the DotNotCore would not, erroring with "specified module could not be found".

After tinkering I saw that the DotNotCoreLibrary was not checked under dependencies. Checking that allowed it to debug properly. I don't know if I did something to mess that up, but figured I'd post it here just in case.

![image](https://user-images.githubusercontent.com/18477601/93325309-1e87a900-f7e5-11ea-814c-177e5fd02f31.png)

**Comment by 3F** [comment]
Thanks for the information!

Looks like I forgot to add this dependency for a new added .NET Core project sample.

@Zinoh, Just open PR and I'll approve it.
