### ISSUE TITLE
Does export work with async ?

### ISSUE THREAD

**Issue by GregDomjan** [3F/Examples#4]
Thinking to convert a method from synchronous to async

```
        [DllExport]
        [return: MarshalAs(UnmanagedType.LPWStr)]
        public static string IsAppRegistered()
        {
            try
            {
                string[] scopes = "User.Read,User.ReadBasic.All".Split(',');
                
                var tokenRequest = tokenAcquisitionHelper.AcquireATokenFromCacheOrIntegratedWindowwAuthenticationAsync(scopes);
                AuthenticationResult authenticationResult = tokenRequest.Result;
            }
```

Have my doubts on if this would be supported at all, or if I am not understanding how to configure it
```
        [DllExport]
        [return: MarshalAs(UnmanagedType.LPWStr)]
        public static async Task<string> IsAppRegistered()
        {
            try
            {
                string[] scopes = "User.Read,User.ReadBasic.All".Split(',');
                
                var tokenRequest = tokenAcquisitionHelper.AcquireATokenFromCacheOrIntegratedWindowwAuthenticationAsync(scopes);
                AuthenticationResult authenticationResult = await tokenRequest;
            }
            catch (MsalUiRequiredException ex) when (ex.Message.Contains("AADSTS65001"))
```

DLL is built, function exported, but on trying to use method it raises the exception about the result

`Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'return value': Generic types cannot be marshaled.`

**Comment by 3F** [comment]
https://github.com/3F/DllExport/wiki/Quick-start#about-data-types

1. async keyword is a C# sugar around Awaiters and Task implementation (+managed Thread & ThreadPool). You can't marshal it as a simple pointer at least until [promises](https://en.wikipedia.org/wiki/Futures_and_promises) are fulfilled.

2. CLR also does not support marshaling of any generic types.
