### ISSUE TITLE
DLLExport Example with by-ref parameters 

### ISSUE THREAD

**Issue by Markus1980Wien** [3F/Examples#5]
Can you please provide an example where a complex type or an arrary of complex types is handed to c# by ref.

Unmanaged code (c++) creates a complex type and fills this type with some data.
Unmanaged code calls an c# Function and hands over the complex type.
c# Reads the data that has been provided by unmanaged code.
c# Modifies the data and hands back the modified data to unmanaged code.
Unmanaged code (c++) uses the data which has been modified by c#.

**Comment by 3F** [comment]
Use IntPtr > [Between unmanaged C++ / C# / Java /... Complex types and Strings. [Part-2]](https://www.youtube.com/watch?v=QXMj9-8XJnY)

\+
https://github.com/3F/Conari/issues/2

```csharp
dlr.somefunc<int>(ref cid, out data);
l.bind<FuncRef4<AVCodecContext, AVPacket, AVFrame, int, int>>("avcodec_encode_audio2")(c, pkt, frame, ref output);
```
